### PR TITLE
v2: review request

### PR DESCRIPTION
**Pull request by JingFu1**
add prerequisites page and solve other bugs

### CODE REVIEW

**Comment by JingFu1** [comment]
Please review this request, thanks!

**Review by Maxinewsu — DISMISSED** [review]
I think this app is good to go.

**Comment by JingFu1** [comment]
Just a reminder, please review that.

**Review by sv101 — COMMENTED** [review]
There are a few issues I noticed when the app is launched.
1. The plots load pretty slow
2. Placing the show test results checkbox at the bottom of the page isn't the best as the user might miss that option
3. For the single proportion tab, I don't think you need to have a population distribution option as there is only one radio button. Rather use a label to explain it.

**Review by sv101 — CHANGES_REQUESTED** [review]
There are a few issues I noticed when the app is launched.

    The plots load pretty slow
    Placing the show test results checkbox at the bottom of the page isn't the best as the user might miss that option
    For the single proportion tab, I don't think you need to have a population distribution option as there is only one radio button. Rather use a label to explain it.

**Comment by JingFu1** [comment]
> There are a few issues I noticed when the app is launched.
> 
> ```
> The plots load pretty slow
> Placing the show test results checkbox at the bottom of the page isn't the best as the user might miss that option
> For the single proportion tab, I don't think you need to have a population distribution option as there is only one radio button. Rather use a label to explain it.
> ```

Thanks for your reviews.

**Comment by hy2021-IT** [comment]
Besides the reviews that were previously stated, everything looks fine.

**Comment by JingFu1** [comment]
> There are a few issues I noticed when the app is launched.
> 
> 1. The plots load pretty slow
> 2. Placing the show test results checkbox at the bottom of the page isn't the best as the user might miss that option
> 3. For the single proportion tab, I don't think you need to have a population distribution option as there is only one radio button. Rather use a label to explain it.

Thanks for your feedbacks!

I made corresponding adjustments to the issues you posted. 1. The original app was slow because it needed 100,000 operations. Now I adjust the number of operations to 30,000 to achieve faster speed and maintain good results. 2. I moved the location of this checkbox. 3. In order to pursue the unity of the format of the two tabs, I didn't modify it.

-Jing

**Comment by JingFu1** [comment]
Hi Everyone, 
Please re-review the app again, I modified it according to the last feedback. Thank you! @sv101 @Maxinewsu @pophillips

**Review by sv101 — DISMISSED** [review]
I could not verify if the app performed over 100k operations initially. However, the app performed without any issues. It's good to go.

**Comment by JingFu1** [comment]
please review the latest version, thanks

**Comment by hy2021-IT** [comment]
Approved

**Review by sv101 — CHANGES_REQUESTED** [review]
Impressive app!
I found a couple of formatting issues:
1. The home button on the top right of the page doesn't show up
2. There is no symbol for the overview tab in the sidebar.

**Review by Maxinewsu — DISMISSED** [review]

**Pull request merged**
